/**
 * UserPreference.js
 * ─────────────────────────────────────────────────────────────
 * MongoDB model — stores everything Atlas learns about a user
 * across conversations. Each user has ONE document that grows
 * over time as Atlas extracts preferences from chat.
 *
 * Drop into:  backend/models/UserPreference.js
 * ─────────────────────────────────────────────────────────────
 */

import mongoose from "mongoose";

const preferenceEntrySchema = new mongoose.Schema(
  {
    key: { type: String, required: true }, // e.g. "seat_preference"
    value: { type: String, required: true }, // e.g. "window seat"
    category: {
      type: String,
      enum: [
        "travel_style", // adventure, luxury, budget, family-friendly
        "accommodation", // hotel brands, room types, amenities
        "flights", // airline, seat, class, layover tolerance
        "food", // dietary restrictions, cuisine preferences
        "activities", // interests, excursion types
        "budget", // spending range, splurge vs save
        "destinations", // favorite/disliked places, bucket list
        "logistics", // packing style, travel companions, pets
        "general", // anything that doesn't fit above
      ],
      default: "general",
    },
    confidence: { type: Number, default: 0.8, min: 0, max: 1 },
    source: { type: String, default: "conversation" }, // "conversation" | "onboarding" | "manual"
    extractedFrom: { type: String }, // the user message that revealed this
    supersedes: { type: String }, // key this replaces (if preference changed)
  },
  { timestamps: true }
);

const tripHistorySchema = new mongoose.Schema(
  {
    destination: String,
    dates: { start: Date, end: Date },
    budget: Number,
    travelers: Number,
    vibe: String,
    rating: { type: Number, min: 1, max: 5 },
    notes: String,
  },
  { timestamps: true }
);

const userPreferenceSchema = new mongoose.Schema(
  {
    userId: { type: String, required: true, unique: true, index: true },

    // ── Core learned preferences ──
    preferences: [preferenceEntrySchema],

    // ── Trip history (past bookings Atlas can reference) ──
    tripHistory: [tripHistorySchema],

    // ── Quick-access summary Atlas injects into every prompt ──
    // Regenerated by preferenceService after each extraction
    profileSummary: { type: String, default: "" },

    // ── Interaction stats (helps Atlas adapt tone/depth) ──
    stats: {
      totalConversations: { type: Number, default: 0 },
      totalMessages: { type: Number, default: 0 },
      firstSeen: { type: Date, default: Date.now },
      lastSeen: { type: Date, default: Date.now },
      topDestinations: [String],
      averageBudget: { type: Number },
    },
  },
  { timestamps: true }
);

// ── Indexes ──
userPreferenceSchema.index({ "preferences.category": 1 });
userPreferenceSchema.index({ "preferences.key": 1 });

// ── Instance: get preferences by category ──
userPreferenceSchema.methods.getByCategory = function (category) {
  return this.preferences.filter((p) => p.category === category);
};

// ── Instance: upsert a single preference ──
userPreferenceSchema.methods.upsertPreference = function (entry) {
  const existing = this.preferences.find(
    (p) => p.key === entry.key && p.category === entry.category
  );
  if (existing) {
    existing.value = entry.value;
    existing.confidence = entry.confidence ?? existing.confidence;
    existing.extractedFrom = entry.extractedFrom || existing.extractedFrom;
    existing.updatedAt = new Date();
  } else {
    this.preferences.push(entry);
  }
};

const UserPreference = mongoose.model("UserPreference", userPreferenceSchema);
export default UserPreference;
